name: Build and Deploy

on:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2.3.1

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Build
        working-directory: ./frontend/discordAttendence/ # <- delete property or modify path if necessary
        run: |
          deno run --allow-run --allow-read https://deno.land/x/snel/install.ts
          trex run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: site
          path: ./frontend/discordAttendence/dist/ # <- modify to your path

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Download Artifacts
        uses: actions/download-artifact@v1
        with:
          name: site

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          branch: deploy # <- modify to wanted branch
          folder: "site"# This is a basic workflow to help you get started with Actions
